locales={};
locales['Svenska | Sverige'] = '?hl=sv&gl=SE&ceid=SE%3Asv';
locales['Tiếng Việt | Việt Nam'] = '?hl=vi&gl=VN&ceid=VN%3Avi';
locales['Türkçe | Türkiye'] = '?hl=tr&gl=TR&ceid=TR%3Atr';
locales['Ελληνικά | Ελλάδα'] = '?hl=el&gl=GR&ceid=GR%3Ael';
locales['Български | България'] = '?hl=bg&gl=BG&ceid=BG%3Abg';
locales['Русский | Россия'] = '?hl=ru&gl=RU&ceid=RU%3Aru';
locales['Русский | Украина'] = '?hl=ru&gl=UA&ceid=UA%3Aru';
locales['Српски | Србија'] = '?hl=sr&gl=RS&ceid=RS%3Asr';
locales['Українська | Україна'] = '?hl=uk&gl=UA&ceid=UA%3Auk';
locales['עברית | ישראל'] = '?hl=he&gl=IL&ceid=IL%3Ahe';
locales['العربية | الإمارات العربية المتحدة'] = '?hl=ar&gl=AE&ceid=AE%3Aar';
locales['العربية | المملكة العربية السعودية'] = '?hl=ar&gl=SA&ceid=SA%3Aar';
locales['العربية | لبنان'] = '?hl=ar&gl=LB&ceid=LB%3Aar';
locales['العربية | مصر'] = '?hl=ar&gl=EG&ceid=EG%3Aar';
locales['मराठी | भारत'] = '?hl=mr&gl=IN&ceid=IN%3Amr';
locales['हिन्दी | भारत'] = '?hl=hi&gl=IN&ceid=IN%3Ahi';
locales['বাংলা | বাংলাদেশ'] = '?hl=bn&gl=BD&ceid=BD%3Abn';
locales['தமிழ் | இந்தியா'] = '?hl=ta&gl=IN&ceid=IN%3Ata';
locales['മലയാളം | ഇന്ത്യ'] = '?hl=ml&gl=IN&ceid=IN%3Aml';
locales['తెలుగు | భారతదేశం'] = '?hl=te&gl=IN&ceid=IN%3Ate';
locales['ไทย | ไทย'] = '?hl=th&gl=TH&ceid=TH%3Ath';
locales['中文 | 中国'] = '?hl=zh-CN&gl=CN&ceid=CN:zh-Hans';
locales['中文 | 台灣'] = '?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant';
locales['中文 | 香港'] = '?hl=zh-HK&gl=HK&ceid=HK%3Azh-Hant';
locales['한국어 | 대한민국'] = '?hl=ko&gl=KR&ceid=KR%3Ako';
console.log(locales);
